export const path = {
  HOME: '/',
  CHAT: '/chat',
  SHOP: '/shop',
  DONATIONS: '/donations',
  DONATION_DETAILS: '/donation-details',
  EVENTS: '/events',
  EVENTS_DETAILS: '/event_details',
  SOCIAL: '/social',
  SOCIAL_DETAIL: '/social/:id',
  GOSSIP: '/gossips',
  PRODUCT: '/product',
  SERVICES: '/services',
  SERVICES_DETAIL: '/services/:id',

  // VENDOR
  VENDOR_SERVICES: '/vendor/services',
  VENDOR_SERVICE_CREATE: '/vendor/services/create',
  VENDOR_EVENTS: '/vendor/events',
  VENDOR_EVENT_LIVE: '/vendor/event-live',
  VENDOR_EVENT_DETAILS: '/vendor/event-details/:id',
  VENDOR_CREATE_EVENT: '/vendor/create-event',
  VENDOR_DONATION: '/vendor/donations',
  VENDOR_DASHBOARD: '/vendor/dashboard',
  VENDOR_SERVICE_DETAIL: '/vendor/services/:id',
  VENDOR_SERVICE_EDIT: '/vendor/services/:id/edit',

  ARTIST: '/vendor/artist',
  ARTIST_ADD_SONG: '/vendor/artist-add-song',
  ARTIST_DASHBOARD: '/vendor/artist-dashboard',
  ARTIST_WALLET: '/vendor/artist-wallet',
  ARTIST_SAVED: '/vendor/artist-saved',
  ARTIST_BOOKING: '/vendor/artist-booking',
  ARTIST_ANALYTICS: '/vendor/artist-analytics',
  ARTIST_CREATE_ACCOUNT: '/vendor/artist-create-account',
  ARTIST_EDIT_PROFILE: '/vendor/artist-edit-profile',

  ARTIST_MAIN_SCREEN:'/artist',
  ARTIST_PROFILE:'/artist-profile',
  SONG_TYPE:'/create-song/song-type',
  SONG_INFO:'/create-song/song-info',
  CHECKOUT:'/create-song/checkout',
  FINAL_CHECKOUT:'/create-song/final-checkout',
  ARTIST_MAIN_BOOKING:'/artist-booking',
};
